#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
previous = 0
current = 1
fibonacci = 0
desiredSum = 0
while True:
	if fibonacci > 4000000:
		break
	fibonacci = previous + current
	previous = current
	current = fibonacci
	if fibonacci % 2 == 0:
		desiredSum += fibonacci 
print(desiredSum)

# Answer: 4613732